import React, { Component } from "react";
import { Model } from 'react-axiom';

class TxnHeader extends Model {

    static defaultState() {
        return {

            CashMOPTotal: "",
            FinanceMOPTotal: "",
            NonFinanceMOPTotal: "",
            TxnId: "",
            ProductVersion: "",
            ReceiptRefID: "",
            TxnTotal: "",
            TxnStatus: "",
            TxnStartTime: "",
            TxnEndTime: "",
            TxnMarkDownReason: "",
            TxnMarkDownReasonDesc: "",
            RoundOffConfigValue: "",
            RoundOffAmount: "",
            PaymentStartTime: "",
            PaymentEndTime: "",
            UserId: "",
            DeviceId: "",
            CustomerName: "",
            EmailID: "",
            ContactNumber: "",
            AddressLine1: "",
            AddressLine2: "",
            AddressLine3: "",
            City: "",
            State: "",
            Pincode: "",
            CustomerID: "",
            LoyaltyCardNumber: "",
            ChangeDue: "",
            isMDTApplied: "",
            TxnDiscValue: "",
            TxnDiscValueFlag: "",
            TxnAppliedDiscValue: "",
            TransactionType: "",
            TxnSalesManID: "",
            PromoTotal: "",
            TxnDiscAppliedTime: "",
            ResumeOrgTxnID: "",
            ResumeOrgPosNum: "",
            ResumeOrgDateTime: "",
            LogonTime: "",
            ItemCount: "",
            ReceiptTextPath: "",
            CurReferenceID: "",
            IsCouponApplied: "",
            Order_Id: "",
            IsAddressCaptured: "",
            ExpectedDeliveryDate: "",
            ExpectedDeliveryTime: "",
            CouponID: "",
            CouponType: "",
            CouponValue: "",
            CouponValueType: "",
            CouponValueParam: "",
            IsLoyaltyCardCaptured: "",
            IsLoyaltyRedeemed: "",
            RedeemAmount: "",
            BalanceLoyaltyPoints: "",
            IsValidLoyaltyRedemption: "",
            IDProofCaptureStatus: "",
            IsIDProofRequiredFlag: "",
            RECEIPTSYNC: "",
            FlatNo: "",
            FloorNo: "",
            BlockNo: "",
            Buildingname: "",
            Societyname: "",
            PlotNo: "",
            Street: "",
            Sector: "",
            Area: "",
            TxnDiscSupervisorID: "",
            DoctorsName: "",
            DoctorsAdd1: "",
            DoctorsAdd2: "",
            DoctorsAdd3: "",
            PatientsName: "",
            PatientsAdd1: "",
            PatientsAdd2: "",
            PatientsAdd3: "",
            OriginalStoreCode: "",
            OriginalTransactionNo: "",
            OriginalTransactionDate: "",
            OriginalPOSNo: "",
            OrderType: "",
        }
    }
}
export default TxnHeader