import React, { Component } from "react";
import { Model } from 'react-axiom';

class TxnItemList extends Model {

    static defaultState() {
        return {
            isPromo,
            isShow,
            ProductID: "",
            SequenceID: "",
            OrgPrice: "",
            SellingPrice: "",
            Quantity: "",
            QuantityAdded: "",
            DiscountID: "",
            DiscountAmount: "",
            DiscountPercentage: "",
            SerialNumber: "",
            IMEI: "",
            DemoReqdorSerialNo: "",
            GiftVoucherNo: "",
            GiftorPrepaidCardNo: "",
            RefNo: "",
            MobileNo: "",
            OrderNo: "",
            AssemblyRequire: "",
            TransactionID: "",
            WiproLimited: "",
            EnterEANorSKU: "",
            SalesmanCode: "",
            EmployeeCode: "",
            ItemType: "",
            Description: "",
            EntryMethod: "",
            ScanTime: "",
            ItemMarkDownReason: "",
            ItemMarkDownDescription: "",
            isMDIApplied: "",
            ItemSellingPrice: "",
            ItemUnitPriceAfterDiscount: "",
            ItemMarkDownDiscountValue: "",
            ItemMarkDownDiscountFlag: "",
            ItemMarkDownDiscountParam: "",
            ItemEmployeeDiscount: "",
            isDiscountApplied: "",
            MaximumQuantity: "",
            MarkDownAllowed: "",
            StockCheckRequired: "",
            StockCount: "",
            QuantityFlag: "",
            SalesManID: "",
            isPromotionAvailableFlag: "",
            isLinkedItemsPresentFlag: "",
            Status: "",
            VoidedDateTime: "",
            ItemDiscAppliedTime: "",
            QtyChangeDateTime: "",
            MDIAppliedDateTime: "",
            TaxID: "",
            TaxChar: "",
            TaxRate: "",
            ReasonCode: "",
            ReasonDesc: "",
            ExpectedDeliveryDate: "",
            DeliveryLocationId: "",
            DeliveryLocation: "",
            UnitOfMeasure: "",
            ItemMesurementType: "",
            IxnId: "",
            DeviceId: "",
            TxnStartTime: "",
            OriginalBarcode: "",
            OriginalPriceWithQty: "",
            DiscountWithQty: "",
            isTradeInItem: "",
            IsCouponApplied: "",
            CouponID: "",
            CouponType: "",
            CouponValue: "",
            CouponValueType: "",
            ExpectedDeliveryTime: "",
            EmbeddedTotalPrice: "",
            CouponValueParam: "",
            AreaScaleBarcode: "",
            PosMsgID: "",
            ExpiryDate: "",
            BatchNumber: "",
            Promo_Amount: "",
            OtherDiscounts: "",
            TaxAmount: "",
            TaxableAmount: "",
            TaxType: "",
            TaxCodeType: "",
            EffectivePrice: "",
            PosMsgDetails: [],

        }
    }
}
export default TxnItemList