const CAFRequest = {
    ACCESSTOKEN: "6d1f7a51-2624-44c9-9253-22c826b2f2d2",//Required for seco
    ALT_Contact_Type: "Mobile",
    AadharDetails_CAF: "",
    AadharTxnRefDateTime: "",
    AadharTxnRefNum: "",
    Aadhar_Number: "",//Done
    Aadharaddrsameinstalltion: "Y",//Done
    Add_readonly: "N",
    AdditionalProducts: "",
    AgentAuthAadharTxnRefDateTime: "",
    AgentAuthAadharTxnRefNo: "",
    AgentName: "",//Done
    Agent_Aadhaar: "",//Done
    Agent_AadharTxnRefDateTime: "",
    Agent_AadharTxnRefNum: "",
    AppointmtDate: "",
    AppointmtFromTime: "",
    AppointmtToTime: "",
    BldgName: "",//Done
    BuildingId: "",//Done
    CAF_NUMBER: "MUH000BJLI",
    CAF_TYPE: "",//Done
    CUPON_CODE: "01",
    CUSTOMER_TYPE: "",//Done
    Caf_Category: "EKYC",
    CareOf: "",//Done
    ChipsTinno: "",
    CircleId: "",//Done
    City: "",//Done
    Country: "",//Done
    CreditScoredate: "",
    CustFamilyIncome: "",
    CustIncome: "",
    CustomerAuthAadharTxnRefDateTime: "",
    CustomerAuthAadharTxnRefNum: "",
    CustomerId: "",
    DG_APIC: "APC;Z00091;0;19.1253073,73.0140548;2020-09-18T11:14:57;",
    DG_ATP: "ATP;Z00092;520048;19.1253123,73.014054;2020-03-04T01:35:00;7021678988;2020-03-04T01:35:00;",
    DG_KYC: "",//Done
    DG_LTP: "LTP;Z00092;156932;19.1253075,73.0140548;2020-03-04T01:35:00;9234343606;2020-03-04T01:35:00;",
    DG_OTP: "OTP;Z00092;423504;19.1253123,73.014054;2020-03-04T01:35:00;9797252821;2020-03-04T01:35:00;",
    DG_PIC: "PIC;Z00091;0;19.1253091,73.0140539;2020-03-04T11:14:29;",
    DG_POA: "",//Done
    DG_POI: "",//Done
    DND: "",
    DOB: "",//Done
    District: "",//Done
    DocumentId: "",
    EID: "",
    Email: "",//Done
    ExistingConnections: "Z02#1#####",
    FACE_AUTH_RESP: "H",
    FFN: "",//Done
    FLN: "",
    FMN: "",
    FM_Agent_Agent: "",
    FM_Cust: "97",
    FM_Cust_AGENT: "0",
    FirstName: "",//Done
    Gender: "",//Done
    Generation_date: "",
    ICCID: "",//Done
    IMEI: "",
    IMSI: "",//Done
    IR: "0",
    ISD: "0",
    InstallationCharges: "0.00",
    JCID: "",//Done
    JiomoneyEKYCResponseCode: "",
    Jiomoney_notify: "N",
    Jiomoneyauthresponsecode: "",
    Jiomoneyauthtimestamp: "",
    JiomoneyekycTimestamp: "",
    LandMark: "",//Done
    LastName: "",
    LocalAdd_Street: "",//Done
    LocalAdd_buildingName: "",//Done
    LocalAdd_landmark: "",//Done
    LocalAdd_locality: "",//Done
    LocalRef_callingpartyNo: "",
    Localadd_City: "",//Done
    Localadd_careof: "",//Done
    Localadd_district: "",//Done
    Localadd_pincode: "",//Done
    Localadd_postoffice: "",//Done
    Localadd_state: "",//Done
    Localadd_subdistrict: "",//Done
    Locality: "",//Done
    Localref_Personcalled: "",
    Localref_noCalled: "",
    MSISDN: "",//Done
    MiddleName: "",
    Mnp_type: "",
    Nationality: "",//Done
    ORN: "",//Done
    PLANID: "",//Done
    POAFLAG: "0",
    POIFLAG: "",
    PRODUCT_ID: "",//Done
    PanNo: "",
    PostCode: "",//Done
    PostOffice: "",
    QR_SCAN_FLAG: "0",
    QR_XML: "",
    R4GID: "",
    RMN: "",//Done
    RMN_relationship: "",//Done
    ReasonMultipleConnection: "",
    Ref_AddType: "",//Done
    Ref_ContactNumber: "",//Done
    Ref_LName: "",//Done
    Ref_MName: "",//Done
    Ref_buildingName: "",//Done
    Ref_city: "",//Done
    Ref_country: "",//Done
    Ref_district: "",//Done
    Ref_fName: "",//Done
    Ref_locality: "",//Done
    Ref_postcode: "",//Done
    Ref_state: "",//Done
    RelationshipType: "0001",
    SERIALNO: "",
    SegmentCodeName: "",
    SegmentCodeValue: "",
    SegmentSubTypename: "",
    SegmentTypename: "",
    ServiceType: "",//Done
    Service_provider_name: "",
    Simtype: "N",
    State: "",//Done
    StoreCity: "",//Done
    StreetName: "",//Done
    SubDistrict: "",
    Subscription_change: "",
    TermCode: "",
    Upc_code: "",
    VANITYFLAG: "Y",
    VanityEAN: "",
    VanityPrice: "",
    VanityType: "NORMAL",
    customerCreditScore: "",
    Inst_Wing: "",
    Inst_Floor: "",
    Inst_Housenameornumber: "",
    Inst_Buildingnameornumber: "",
    Inst_Societyname: "",
    Inst_Areaortehsil: "",
    Inst_Landmark: "",
    Inst_Sublocality: "",
    Inst_Streetnameornumber: "",
    Inst_Pincode: "",
    Inst_City: "",
    Inst_District: "",
    Inst_State: "",
    Inst_Totalfloors: "",
    Inst_CareOf: "",
    AgentToken: "",
    CustomerToken: "",
    RMN_RELATIONSHIP:"KNOWN PERSON"

}

export default CAFRequest;