import React, { Component } from "react";
import { Model } from 'react-axiom';

class TxnHeader extends Model {

    static defaultState() {
        return {
            
            TxnCNC_Number: "",
            TxnStartTime: "",
            TxnCouponSupervisorID: "",
            IsVatExtra: "",
            ExpectedDeliveryTime: "",
            OriginalTransactionDate: "",
            Pincode: "",
            CouponValue: "",
            LogonTime: "",
            CouponValueParam: "",
            NonFinanceMOPTotal: "",
            BuildingName: "",
            Store_CSTDate: "",
            RECEIPTSYNC: "",
            TxnMarkDownReason: "",
            ContactNumber: "",
            RoundOffConfigValue: "",
            OriginalPOSNo: "",
            LoyaltyCardNumber: "",
            IsLoyaltyRedeemed: "",
            FinanceMOPTotal: "",
            CashMOPTotal: "",
            OriginalTransactionNo: "",
            TotalAddnlTax: "",
            CustomerID: "",
            BlockNo: "",
            Order_Id: "",
            AddressLine1: "",
            TxnId: "",
            TxnMarkDownReasonDesc: "",
            AddressLine2: "",
            AddressLine3: "",
            ProductVersion: "",
            PlotNo: "",
            Street: "",
            PatientsName: "",
            PanCardNo: "",
            TxnCNC_INVOICETYPE: "",
            isMDTApplied: "",
            PatientsAdd3: "",
            PromoTotal: "",
            TaxInvoice: "",
            TransactionType: "",
            Societyname: "",
            CouponID: "",
            ResumeOrgDateTime: "",
            TxnCNC_DATECST: "",
            DeviceId: "",
            TxnCNC_AddrL2: "",
            PaymentEndTime: "",
            TxnCNC_AddrL3: "",
            TxnCNC_AddrL1: "",
            UserId: "",
            DoctorsAdd1: "",
            IsIDProofRequiredFlag: "",
            DoctorsAdd2: "",
            City: "",
            DoctorsAdd3: "",
            CouponType: "",
            Supply_State_Code: "",
            IsValidLoyaltyRedemption: "",
            SocietyName: "",
            Sector: "",
            TxnDiscValueFlag: "",
            Area: "",
            TxnCNC_CSTNO: "",
            TxnCNC_DATELST: "",
            ChangeDue: "",
            ReceiptTextPath: "",
            ExpectedDeliveryDate: "",
            DoctorsName: "",
            RedeemAmount: "",
            IsCouponApplied: "",
            ESOrderID: "",
            CurReferenceID: "",
            XmlGeneratedFlag: "",
            ResumeOrgTxnID: "",
            VoidTxnSupervisorID: "",
            IDProofCaptureStatus: "",
            TotalSurcharge: "",
            TxnDiscAppliedTime: "",
            ItemCount: "",
            Store_LST: "",
            PatientsAdd2: "",
            PatientsAdd1: "",
            TxnCNC_LSTNO: "",
            CustomerName: "",
            FloorNo: "",
            TaxableAmount: "",
            TotalTaxAmount: "",
            TxnCNC_Name: "",
            TxnCNC_INVOICENO: "",
            TxnAppliedDiscValue: "",
            IsLoyaltyCardCaptured: "",
            BillOfSupply: "",
            RoundOffAmount: "",
            OriginalStoreCode: "",
            ReceiptRefID: "",
            TxnDiscSupervisorID: "",
            TxnDiscValue: "",
            RefundTxnSupervisorID: "",
            BalanceLoyaltyPoints: "",
            StoreId: "",
            OrderType: "",
            TotalVAT: "",
            PaymentStartTime: "",
            FlatNo: "",
            EmailId: "",
            IsAddressCaptured: "",
            Store_CST: "",
            Buildingname: "",
            IsTaxCalculationRequired: "",
            TxnStatus: "",
            TxnEndTime: "",
            Store_LSTDate: "",
            TxnTotal: "",
            TxnSalesManID: "",
            CouponValueType: "",
            State: "",
            ResumeOrgPosNum: "",
            EmailID: "",
            MNP_MSISDN: "",
            ZONE: "",

        }
    }
}

export default TxnHeader;