import React, { Component } from "react";
import { Model } from 'react-axiom';
class TxnItemList extends Model {

    static defaultState() {
        return {
            
            DiscountID: "",
            TxnStartTime: "",
            WiproLimited: "",
            ExpectedDeliveryTime: "",
            QuantityFlag: "",
            DiscountWithQty: "",
            isPromotionAvailableFlag: "",
            DiscountAmount: "",
            DeliveryLocation: "",
            QtyChangeDateTime: "",
            VoidedDateTime: "",
            OriginalBarcode: "",
            CouponValue: "",
            ItemMarkDownDiscountFlag: "",
            OrgSeqId: "",
            CouponValueParam: "",
            SupervisorID: "",
            LocationType: "",
            strFoodStamp: "",
            TaxDetails ,
            AreaScaleBarcode: "",
            ItemSellingPrice: "",
            isSeqId: "",
            isMDIApplied: "",
            ScanTime: "",
            ExpiryDate: "",
            GiftVoucherNo: "",
            ItemEmployeeDiscount: "",
            DiscountPercentage: "",
            TxnId: "",
            ReasonDesc: "",
            isPromoData: "",
            DeliveryLocationId: "",
            isPharmacy: "",
            MarkDownAllowed: "",
            ItemType: "",
            UnitOfMeasure: "",
            CouponID: "",
            GiftorPrepaidCardNo: "",
            BatchNumber: "",
            ItemMarkDownDescription: "",
            DeviceId: "",
            TxnItemPromoDetails : [],
            ItemDiscAppliedTime: "",
            EntryMethod: "",
            ValidatedPosMsgId: "",
            ParentReferenceID: "",
            SequenceID: "",
            EnterEANorSKU: "",
            CouponType: "",
            SalesManID: "",
            AssemblyRequire: "",
            LnkItemList :[],
            ItemMarkDownReason: "",
            ItemMarkDownDiscountParam: "",
            isVoidAllowed: "",
            IMEI1: "",
            ReasonCode: "",
            ItemMarkDownSupervisorID: "",
            MDIAppliedDateTime: "",
            MobileNo: "",
            SerialNumber: "",
            TransactionID: "",
            OrderNo: "",
            isHomeDeliveryItem: "",
            StockCheckRequired: "",
            ExpectedDeliveryDate: "",
            IsCouponApplied: "",
            XmlGeneratedFlag: "",
            MaximumQuantity: "",
            Promo_Amount: "",
            StockCount: "",
            isLinkedItemsPresentFlag: "",
            OtherDiscounts: "",
            CouponSupervisorID: "",
            EmployeeCode: "",
            ItemMesurementType: "",
            ItemUnitPriceAfterDiscount: "",
            RefNo: "",
            IsvoidAllowedKYC: "",
            DemoReqdorSerialNo: "",
            ProductID: "",
            isDiscountApplied: "",
            isTradeInItem: "",
            OrgPrice: "",
            HSN_CODE: "",
            EffectivePrice: "",
            VoidSupervisorID: "",
            QuantityAdded: "",
            Description: "",
            Quantity: "",
            PosMsgDetails : [],
            SalesmanCode: "",
            ItemMarkDownDiscountValue: "",
            OriginalPriceWithQty: "",
            Status: "",
            CouponValueType: "",
            IMEI: "",
            StoreID: "",
            SellingPrice: "",
            EmbeddedTotalPrice: "",
            ItemEmpDiscSupervisorID: "",
            TRNO: "",
            MD_FG: "",
            ReasonFreeText: "",
            SearchStatus: "",
            isHDChildWithZeroPrice: "",
            itm_point: "",
            prom_nbr: "",
            Extnd_prom_nbr: "",
            Extnd_bckt_nbr: "",
            Stylecode: "",
            Colorcode: "",
            ProductJewelDetails: "",

        }
    }
}
export default TxnItemList;
