export const LOADING_OPERATION = 'LOADING_OPERATION';
export const STORE_CUSTOMER_CIRCLE = 'STORE_CUSTOMER_CIRCLE';
export const STORE_CUSTOMER_DELIVERY = 'STORE_CUSTOMER_DELIVERY';
export const STORE_CUSTOMER_NUMBER = 'STORE_CUSTOMER_NUMBER';
export const STORE_CUSTOMER_OUTSTATION = 'STORE_CUSTOMER_OUTSTATION';
export const STORE_CUSTOMER_PERMANENT = 'STORE_CUSTOMER_PERMANENT';



